name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.x'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/jianshu-server:latest
          build-args: |
            PNPM_BUILD_OPTS=--shamefully-hoist

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ./deploy.sh
            ./deploy.sh
